## Numpy Array Oluşturma

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.random.randint(10, size=10)

array([6, 5, 9, 7, 4, 3, 5, 8, 3, 3])

In [9]:
np.random.normal(10,4,(3,4))

array([[12.8865157 ,  6.86531055,  0.97292127,  9.01067824],
       [10.91560256, 11.36034035,  8.5827896 ,  8.53603431],
       [11.05064551,  5.78048978, 13.92777297, 12.63119102]])

In [10]:
?np.random.normal

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single v

In [11]:
np.random.randint(0,10, (4,3))

array([[3, 5, 8],
       [2, 6, 4],
       [2, 5, 8],
       [2, 2, 5]])

- ndim : boyut sayısı
- shape : boyut bilgisi
- size : toplam elemen sayısı
- dtype : array veri tipi

In [34]:
a = np.random.randint(10, size=10)

In [35]:
a

array([5, 5, 0, 1, 3, 3, 9, 0, 1, 6])

In [36]:
a.ndim

1

In [37]:
a.shape

(10,)

In [38]:
a.size

10

In [39]:
a.dtype

dtype('int64')

In [29]:
b = np.random.randint(10, size=(3,5))

In [24]:
b

array([[6, 6, 3, 8, 1],
       [8, 5, 8, 0, 4],
       [3, 1, 6, 2, 6]])

In [30]:
b.ndim

2

In [31]:
b.shape

(3, 5)

In [32]:
b.size

15

In [33]:
b.dtype

dtype('int64')

## Yeniden Şekillendirme (Reshaping)

In [40]:
import numpy as np

In [41]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Birleştirme (Concatenation)

In [45]:
import numpy as np

In [46]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [47]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [50]:
z = np.array([7,8,9])

In [51]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#iki boyut

In [53]:
a = np.array([[1,2,3],
             [4,5,6]])

In [54]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [56]:
import numpy as np

In [58]:
x = np.array([1,2,3,99,99,3,2,1])

In [59]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [60]:
a,b,c = np.split(x, [3,5])

In [61]:
a

array([1, 2, 3])

In [62]:
b

array([99, 99])

In [63]:
c

array([3, 2, 1])

In [64]:
# iki boyutlu ayırma

In [66]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [70]:
ust, alt = np.vsplit(m, [2])

In [71]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [78]:
sag, sol = np.hsplit(m, [2])

In [79]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [80]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [82]:
import numpy as np

In [83]:
v = np.array([2,1,4,3,5])

In [84]:
v

array([2, 1, 4, 3, 5])

In [85]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [86]:
v

array([2, 1, 4, 3, 5])

In [87]:
v.sort()

In [88]:
v

array([1, 2, 3, 4, 5])

In [89]:
#iki boyutlu array sıralama

In [90]:
m = np.random.normal(20,5,(3,3))

In [91]:
m

array([[12.05488897, 21.2488028 , 17.26350332],
       [16.24587051, 22.94738366, 18.29503199],
       [28.49396337, 21.0801818 , 25.30223282]])

In [92]:
np.sort(m, axis=1)

array([[12.05488897, 17.26350332, 21.2488028 ],
       [16.24587051, 18.29503199, 22.94738366],
       [21.0801818 , 25.30223282, 28.49396337]])

In [93]:
np.sort(m, axis=0)

array([[12.05488897, 21.0801818 , 17.26350332],
       [16.24587051, 21.2488028 , 18.29503199],
       [28.49396337, 22.94738366, 25.30223282]])

## Index ile Elemanlara Erişmek

In [94]:
import numpy as np

In [97]:
a = np.random.randint(10, size = 10)
a

array([5, 9, 9, 8, 8, 4, 0, 7, 1, 3])

In [98]:
a[0]

5

In [99]:
a[-1]

3

In [100]:
a[0] = 100

In [101]:
a

array([100,   9,   9,   8,   8,   4,   0,   7,   1,   3])

In [103]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 6, 8, 8, 3],
       [5, 7, 4, 5, 8],
       [7, 0, 8, 9, 4]])

In [104]:
m[0,0]

6

In [105]:
m[1,1]

7

In [108]:
m[0:2]

array([[6, 6, 8, 8, 3],
       [5, 7, 4, 5, 8]])

In [109]:
m[:,0]

array([6, 5, 7])

In [110]:
m[1,:]

array([5, 7, 4, 5, 8])

In [111]:
m[0:2,0:3]

array([[6, 6, 8],
       [5, 7, 4]])

In [112]:
# Index
# Slicing
# Fancy

## Fancy Index

In [113]:
import numpy as np

In [115]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [116]:
v[1]

3

In [117]:
v[4]

12

In [118]:
al_getir = [1,2,3]

In [119]:
v[al_getir]

array([3, 6, 9])

In [120]:
m = np.arange(9).reshape((3,3))

In [121]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
m[0,[1,2]]

array([1, 2])

In [123]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
m[0:1, [1,2]]

array([[1, 2]])

## Koşullu Eleman İşlemleri

In [126]:
import numpy as np

In [127]:
v = np.array([1,2,3,4,5])

In [128]:
v

array([1, 2, 3, 4, 5])

In [130]:
ab = []

for i in v:
    if i < 3:
        ab.append(i)

In [131]:
ab

[1, 2]

In [132]:
v[v<3]

array([1, 2])

In [133]:
v

array([1, 2, 3, 4, 5])

In [134]:
v<3

array([ True,  True, False, False, False])

In [135]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [136]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [137]:
v**2

array([ 1,  4,  9, 16, 25])

In [138]:
v-1

array([0, 1, 2, 3, 4])

In [139]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [140]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [141]:
np.mean(v)

3.0

In [142]:
v.sum()

15

In [143]:
v.min()

1

## Pandas DataFrame Oluşturma

- Panel Data

- Veri manipülasyonu ve veri analizi için açık kaynak kodlu bir python kütüphanesidir.

- Ekonometrik ve finansal çalışmalar için doğmuştur.
- Temeli 2008 yılında atılmıştır.

- R DataFrame yapısını Python dünyasına taşımış ve DataFrame'ler üzerinde hızlı ve etkili çalışabilme imkanı sağlamıştır.

- Bir çok farklı veri tipini okuma ve yazma imkanı sağlar. 

In [147]:
import pandas as pd

In [144]:
l = [1,2,39,67,90]

In [145]:
l

[1, 2, 39, 67, 90]

In [151]:
df = pd.DataFrame(l, columns = ["degisken_ismi"])

In [152]:
df

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [153]:
type(df)

pandas.core.frame.DataFrame

In [154]:
import numpy as np

In [157]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
type(m)

numpy.ndarray

In [160]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [161]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])

In [162]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [164]:
df.head() #ilk 5

var1  var2  var3
0     1     2     3
1     4     5     6

In [166]:
df.tail() #son 5

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [167]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [168]:
df.columns = ["degisken1","degisken2","degisken3"]

In [169]:
df

degisken1  degisken2  degisken3
0          1          2          3
1          4          5          6
2          7          8          9

In [170]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['degisken1', 'degisken2', 'degisken3'], dtype='object')]

In [171]:
df.shape

(3, 3)

In [172]:
df.ndim

2

In [173]:
df.size

9

In [174]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
type(df.values)

numpy.ndarray

## Eleman İşlemleri

In [176]:
import numpy as np

In [177]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [178]:
s1

array([8, 2, 5, 4, 8])

In [179]:
type(s1)

numpy.ndarray

In [180]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [181]:
sozluk

{'var1': array([8, 2, 5, 4, 8]),
 'var2': array([8, 2, 3, 1, 1]),
 'var3': array([7, 3, 5, 5, 2])}

In [182]:
df = pd.DataFrame(sozluk)

In [183]:
df

var1  var2  var3
0     8     8     7
1     2     2     3
2     5     3     5
3     4     1     5
4     8     1     2

In [184]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [185]:
df.index = ["a","b","c","d","e"]

In [186]:
df

var1  var2  var3
a     8     8     7
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

In [187]:
df["c":"e"]

var1  var2  var3
c     5     3     5
d     4     1     5
e     8     1     2

In [189]:
df.drop("a", axis=0)

var1  var2  var3
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

In [190]:
df

var1  var2  var3
a     8     8     7
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

In [191]:
df.drop("a", axis=0, inplace = True)

In [192]:
df

var1  var2  var3
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

In [193]:
l = ["c","e"]

In [194]:
df.drop(l, axis = 0)

var1  var2  var3
b     2     2     3
d     4     1     5

In [195]:
#değişkenler

In [196]:
df

var1  var2  var3
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

In [197]:
?df.drop

Signature:
df.drop(
    labels=None,
    axis=0,
    index=None,
    columns=None,
    level=None,
    inplace=False,
    errors='raise',
)
Docstring:
Drop specified labels from rows or columns.

Remove rows or columns by specifying label names and corresponding
axis, or by specifying directly index or column names. When using a
multi-index, labels on different levels can be removed by specifying
the level.

Parameters
----------
labels : single label or list-like
    Index or column labels to drop.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
    columns (1 or 'columns').
index : single label or list-like
    Alternative to specifying axis (``labels, axis=0``
    is equivalent to ``index=labels``).

    .. versionadded:: 0.21.0
columns : single label or list-like
    Alternative to specifying axis (``labels, axis=1``
    is equivalent to ``columns=labels``).

    .. versionadded:: 0.21.0
level : int or level name, optiona

In [198]:
"var1" in df 

True

In [199]:
"var8" in df

False

In [202]:
df[["var1"]] #iki köşeli parantez dataframe kalmasını sağlıyor

var1
b     2
c     5
d     4
e     8

In [203]:
type(df["var1"])

pandas.core.series.Series

In [204]:
df

var1  var2  var3
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

In [207]:
df["var4"] = df["var1"] / df["var2"]

In [208]:
df

var1  var2  var3      var4
b     2     2     3  1.000000
c     5     3     5  1.666667
d     4     1     5  4.000000
e     8     1     2  8.000000

In [209]:
df.drop("var4", axis = 1 , inplace = True)

In [210]:
df

var1  var2  var3
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

In [214]:
l =["var1","var2"]

In [216]:
df.drop(l,axis=1)

var3
b     3
c     5
d     5
e     2

In [217]:
df

var1  var2  var3
b     2     2     3
c     5     3     5
d     4     1     5
e     8     1     2

## iloc & loc

In [220]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    13     7    15
1    19    16    16
2    27    24    20
3     7     4    28
4    14    26    25
5    29    12    17
6    21    14    19
7    10    24    18
8    22    18     4
9    24     3    22

In [221]:
#iloc: integer based selection

In [223]:
df.iloc[0:3]

var1  var2  var3
0    13     7    15
1    19    16    16
2    27    24    20

In [225]:
df.iloc[0,0]

13

In [226]:
#loc: label based selection

In [227]:
df.loc[0:3]

var1  var2  var3
0    13     7    15
1    19    16    16
2    27    24    20
3     7     4    28

In [230]:
df[0:3,"var3"]

TypeError: '(slice(0, 3, None), 'var3')' is an invalid key

In [231]:
df.iloc[0:3,"var3"]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [232]:
df.loc[0:3,"var3"]

0    15
1    16
2    20
3    28
Name: var3, dtype: int64

In [235]:
df.iloc[0:3][["var3"]]

var3
0    15
1    16
2    20

In [236]:
l = ["var1","var2"]

In [237]:
df.loc[0:3,l]

var1  var2
0    13     7
1    19    16
2    27    24
3     7     4

## koşullu seçim

In [238]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    18     8    17
1    24     9    13
2    14     4    23
3     7    20    10
4    10    28     8
5     9    14     1
6    10    14    11
7    19    14    21
8    26    26    20
9    14    12    20

In [239]:
df["var1"]

0    18
1    24
2    14
3     7
4    10
5     9
6    10
7    19
8    26
9    14
Name: var1, dtype: int64

In [240]:
df[["var1","var2"]]

var1  var2
0    18     8
1    24     9
2    14     4
3     7    20
4    10    28
5     9    14
6    10    14
7    19    14
8    26    26
9    14    12

In [241]:
df[0:2][["var1","var2"]]

var1  var2
0    18     8
1    24     9

In [242]:
df["var1"] > 5

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: var1, dtype: bool

In [244]:
df[df["var1"] > 6]

var1  var2  var3
0    18     8    17
1    24     9    13
2    14     4    23
3     7    20    10
4    10    28     8
5     9    14     1
6    10    14    11
7    19    14    21
8    26    26    20
9    14    12    20

In [245]:
df[df["var1"] > 6]["var2"]

0     8
1     9
2     4
3    20
4    28
5    14
6    14
7    14
8    26
9    12
Name: var2, dtype: int64

In [246]:
df.loc[df["var1"] > 6,"var2"]

0     8
1     9
2     4
3    20
4    28
5    14
6    14
7    14
8    26
9    12
Name: var2, dtype: int64

In [252]:
 df[(df["var1"] > 6) & (df["var2"]>3)]

var1  var2  var3
0    18     8    17
1    24     9    13
2    14     4    23
3     7    20    10
4    10    28     8
5     9    14     1
6    10    14    11
7    19    14    21
8    26    26    20
9    14    12    20

In [253]:
 df.loc[(df["var1"] > 6) & (df["var2"]>3),["var1","var2"]]

var1  var2
0    18     8
1    24     9
2    14     4
3     7    20
4    10    28
5     9    14
6    10    14
7    19    14
8    26    26
9    14    12